default: &default
  adapter: mysql2
  username: root
  password:
  host: localhost
  reconnect: true
  local_infile: true
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: money_mustache_development

test:
  <<: *default
  database: money_mustache_test
